"""Initial migration

Revision ID: 239ee3a414bf
Revises: 
Create Date: 2026-05-25 08:42:19.891770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239ee3a414bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('fix_applied', sa.Text(), nullable=False),
    sa.Column('what_did_not_work', sa.Text(), nullable=True),
    sa.Column('iterations_needed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_summaries_error_type'), 'repair_summaries', ['error_type'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('original_code', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_iterations', sa.Integer(), nullable=False),
    sa.Column('final_code', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('experiment_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_status_created', 'submissions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_submissions_case_id'), 'submissions', ['case_id'], unique=False)
    op.create_index(op.f('ix_submissions_category'), 'submissions', ['category'], unique=False)
    op.create_index(op.f('ix_submissions_experiment_id'), 'submissions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('iterations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_num', sa.Integer(), nullable=False),
    sa.Column('code_input', sa.Text(), nullable=False),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('error_logs', sa.Text(), nullable=True),
    sa.Column('boost_context', sa.Text(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('planner_model', sa.String(length=100), nullable=True),
    sa.Column('executor_model', sa.String(length=100), nullable=True),
    sa.Column('reviewer_model', sa.String(length=100), nullable=True),
    sa.Column('patch_applied', sa.Text(), nullable=True),
    sa.Column('pest_test_code', sa.Text(), nullable=True),
    sa.Column('pest_test_result', sa.Text(), nullable=True),
    sa.Column('mutation_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('failure_details', sa.Text(), nullable=True),
    sa.Column('pm_category', sa.String(length=50), nullable=True),
    sa.Column('pm_strategy', sa.Text(), nullable=True),
    sa.Column('pipeline_logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iterations')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_experiment_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_category'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_case_id'), table_name='submissions')
    op.drop_index('idx_submissions_status_created', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_repair_summaries_error_type'), table_name='repair_summaries')
    op.drop_table('repair_summaries')
    # ### end Alembic commands ###
